# Generated by Django 5.2.2 on 2025-06-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercloudprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercloudprovider',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
