# Generated by Django 5.2.2 on 2025-06-09 15:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0002_usercloudprovider_email_usercloudprovider_extra_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercloudprovider',
            unique_together={('user', 'provider_name', 'email')},
        ),
    ]
